/**
 * Auto-generated GetSign knowledge base, extracted from getsign.io
 * (getting-started guides, how-tos, capability pages, FAQ, blog) on 2026-06-20.
 *
 * Bodies are faithful to the source pages — product facts and step-by-step
 * instructions only. Re-generate by re-crawling the sitemap when the product
 * changes. Merged with the curated entries in getsign-kb.ts.
 */
import type { KbArticle } from "./getsign-kb";

export const GETSIGN_GENERATED: KbArticle[] = [
  {
    title: "How to use GetSign in monday.com subitems",
    url: "https://getsign.io/getting-started/getsign-now-works-in-monday-com-subitems/",
    source: "getsign.io",
    keywords: ["subitems", "monday.com", "getsign", "upload template", "docx", "signature field", "field mapping", "automation", "status trigger", "file column", "esignature", "send document", "track signing"],
    body: `GetSign runs document workflows directly inside monday.com subitems. To enable it, open any subitem, select Add View, then Explore More Views, and choose GetSign; it activates across all subitems on that board automatically. Upload a template: in the GetSign view click Upload Template and select a DOCX file; it opens in a new tab in the GetSign editor. Map board fields: click Edit Template and map board fields (Item Name, date columns, etc.) into the document; use Preview to verify, then save. Place signature fields: in the PDF editor, drag signature, name, and date picker fields onto the document and assign each to specific signers by email, then save. Configure automation: in the Generate section enable generation and select the status value that triggers it, choose the file column for the PDF, and set a document name; in the Sign section enable signature collection, select the triggering status, and pick the column for the signed file. Generate, send, and track: change the item status to trigger generation; the document saves to the file column. Click Send Now or let automation dispatch to signers. Track progress under the Sign tab.`,
  },
  {
    title: "Getting started with GetSign on monday.com",
    url: "https://getsign.io/getting-started/getsign/",
    source: "getsign.io",
    keywords: ["getsign", "install", "monday.com marketplace", "add view", "status column", "email column", "files column", "field mapping", "signature field", "otp", "email verification", "docx", "pdf", "copy link", "send for signature"],
    body: `Install GetSign by searching for it in the monday.com App marketplace, clicking Add to your account, and completing authorization. On your board, click + to add a view and select GetSign. Create columns for status, email, and files; default statuses load initially and more appear after signing completes. Uploading supports DOCX or PDF. Options: Select (choose a document), eye icon (view), pencil icon (edit in the GetSign editor), copy icon (duplicate without affecting the original). You can attach several documents per item and send them together; if you send multiple documents and the client declines even one, the entire set is declined. Field mapping: in the GetSign tab, map each field to the corresponding board columns and Save. Email customization: set sender name and email, subject, message, company logo, language, and an OTP option; email verification is required before sending to avoid spam flagging. Signature fields: in Settings use the pencil icon to edit, drag the Signature field to the location, and select the email column to assign it — ensure that email column is not empty, otherwise the email will not be sent. Sending options: Preview, Copy Link, Download, and Send. Recipients get a Review & Sign email, add their signature, then save.`,
  },
  {
    title: "How to collect form responses with sharable online forms and map them to documents",
    url: "https://getsign.io/getting-started/collect-form-responses-using-sharable-online-forms/",
    source: "getsign.io",
    keywords: ["online form", "sharable form", "monday.com form", "form builder", "collect responses", "board columns", "embed form", "share form link", "field mapping", "board fields", "prepopulated document", "esignature", "no-code"],
    body: `Create a sharable online form on monday.com using the no-code form builder. Open your board, click the + icon next to existing views, and select Form; the system automatically converts board columns into fillable fields. Customize fields: add or edit columns in your board before creating the form, rename field labels, add placeholder text or descriptions, and select field types such as text, dropdowns, dates, and checkboxes. Share the form: click Share Form to generate a shareable URL; anyone with the link can complete the form without a monday.com account. Optionally embed it on websites using the provided embed code, and distribute via email or chat. Map form data to documents with GetSign: switch to the GetSign view on items created by form submissions, and in the document editor drag Board Fields onto your template and map each field (name, email, project details) to the corresponding board columns. Then send the pre-populated document for eSignature — an automated workflow from form submission through eSignature without manual data entry.`,
  },
  {
    title: "How to combine uploaded templates and stored documents in one signature envelope",
    url: "https://getsign.io/getting-started/how-to-combine-uploaded-templates-and-stored-documents/",
    source: "getsign.io",
    keywords: ["combine documents", "uploaded template", "stored documents", "use stored documents", "signature envelope", "docx", "pdf", "file column", "signature fields", "getsign editor", "signing link", "signed documents column", "monday.com"],
    body: `GetSign lets you send both an uploaded DOCX template and a stored board document together in a single signature envelope (both DOCX and PDF work in combination). Steps: (1) Open the GetSign item view; add the item view if not enabled. (2) Upload a template: in Templates and Documents select Add a New Template and upload your DOCX — the editor opens. (3) Add signature fields to the template by drag and drop, save, and close. (4) Enable stored documents: toggle Use Stored Documents ON and select the file column containing your supporting document. (5) Add signature fields to the stored document: click the edit icon next to it, add signature fields, and save. (6) Configure signature settings: set the status and file columns for tracking, enter and verify the sender email if required, and save. (7) Send: click Share and choose email or signing-link delivery; the recipient receives both documents as one workflow. (8) Signed files appear in the designated Signed Documents column; verify completion across both documents.`,
  },
  {
    title: "How to generate a single-signer document signing link",
    url: "https://getsign.io/getting-started/generate-a-document-signing-link-for-a-single-signer/",
    source: "getsign.io",
    keywords: ["signing link", "single signer", "generate link", "share option", "status trigger", "file column", "copy link", "whatsapp", "slack", "sms", "getsign", "monday.com", "share and track", "automated link"],
    body: `GetSign offers two ways to create a signing link: manual generation via the item view's Share option, and automated generation triggered by status updates. Manual: (1) Open your item and access the GetSign view with an uploaded template. (2) Click Edit Template, drag a Signature Field into the document, and Save. (3) In the item view select Share. (4) Click Generate Link. (5) The link appears in a designated column (e.g., Signing Link) and can be copied to share via WhatsApp, Slack, SMS, or other messaging. Automated (status-based): (1) Open GetSign Share and Track settings. (2) Select a Status Column as the trigger. (3) Set the trigger value (e.g., Done). (4) Choose a File Column where the link is saved. (5) Save. (6) Change the item's status to the trigger value; GetSign generates and stores the link automatically. This is useful for single-signer workflows and field-based signers, lets you share over chat/SMS, skip email invitations, and keep tracking on your board.`,
  },
  {
    title: "How to customize a document for each client on monday.com",
    url: "https://getsign.io/getting-started/customize-document-for-each-client-on-monday-com/",
    source: "getsign.io",
    keywords: ["customize document", "per client", "docx template", "per-item", "envelope document", "edit icon", "master template", "preview", "signature field", "share", "monday.com", "getsign editor", "save template"],
    body: `GetSign allows per-item document customization, letting you tailor a DOCX template for an individual client without duplicating templates or changing the master version. This is available only for DOCX templates; PDFs do not support per-item content customization. Steps: (1) Upload template: open the GetSign item view, select Add Template, and upload your DOCX (e.g., a proposal). (2) Add interactive fields in the editor (signature, date, text inputs), Save, and close; the template appears in the Envelope Document section. (3) Preview the default version to identify sections to customize (pricing tiers, packages). (4) Customize per client: in the Envelope Document section click the edit icon — this applies only to that item; the master template is unchanged. Modify content, then Save Template. (5) Send via the Share option (email or signing link); recipients see only their customized version. (6) Verify the signed document to confirm edits. The original template remains reusable.`,
  },
  {
    title: "How to generate PDF documents for eSignatures",
    url: "https://getsign.io/getting-started/generate-pdf-documents-for-esignatures/",
    source: "getsign.io",
    keywords: ["generate pdf", "document generation", "getsign generate", "status trigger", "pin file", "docx", "pdf", "template", "file column", "board data", "generate button", "esignature", "monday.com"],
    body: `GetSign automates PDF creation using live monday.com board data (names, emails, dates, status). Step 1 - Enable generation: in GetSign settings toggle on GetSign Generate, select a board column and a specific label (e.g., Generate Now) as the trigger; for DOCX uploads choose PDF or DOCX output. Step 2 - Upload and activate template: upload your template (DOCX or PDF). The file must be pinned in the document field to become active — pinning is required for generation; unpinned files will not trigger creation (default uploads remain unpinned). Step 3 - Generate: after configuration a Generate button appears in the item view for manual triggering, or changing an item's status to your label creates the document automatically. Step 4 - Access files: generated documents appear in the File column, where users can view, download, or route them for signing. Constraints: accepted formats are DOCX and PDF; files must be pinned; each workflow can use different templates and conditions; generated documents store in item file columns.`,
  },
  {
    title: "How to securely store signed documents on monday.com",
    url: "https://getsign.io/getting-started/securely-store-signed-documents/",
    source: "getsign.io",
    keywords: ["store signed documents", "secure storage", "completed documents", "file column", "lock column", "column permissions", "audit trail", "signature metadata", "access logs", "monday.com", "getsign", "install", "hipaa"],
    body: `GetSign automatically stores signed documents (Completed Documents) in a locked File column on monday.com boards, restricting access to authorized users. Steps: (1) Install GetSign from the monday.com Apps Marketplace. (2) Create a File column: click the + icon next to your columns and select Files. (3) Restrict access: lock the File column to limit visibility to specific account users, and use column permissions to control who can view or download. Key features: completed documents save to the File column immediately on signature completion; permission controls designate who can access stored files; each file includes audit trails with timestamps, signature metadata, and access logs. Works with document generation, sign-by-link, and signing-order workflows. Use cases: employment contracts, client agreements, financial documents, legal disclosures, HIPAA-compliant medical records, and vendor contracts/MOUs.`,
  },
  {
    title: "Supported email languages for eSignature requests",
    url: "https://getsign.io/getting-started/supported-email-language/",
    source: "getsign.io",
    keywords: ["email language", "multilingual", "supported languages", "english", "french", "hebrew", "portuguese", "spanish", "japanese", "localization", "settings", "per-recipient", "esignature"],
    body: `GetSign supports six email languages: English, French, Hebrew, Portuguese, Spanish, and Japanese. Only system-generated email components are translated (subject lines, headers, call-to-action buttons, instructions). The document content itself is NOT translated; if you need a localized document, upload a localized version separately. To set the email language: upload your document, go to the Settings tab, select the desired email language, then send the request — recipients receive emails in that language. Per-recipient language selection is available, so different recipients can receive different languages. The sender controls the language; recipients cannot change their own preference. Localization does not affect encryption, audit trails, or the legal binding of signatures. Emails adapt to mobile and desktop.`,
  },
  {
    title: "Secure documents with OTP authentication",
    url: "https://getsign.io/getting-started/secure-documents-with-otp-authentication/",
    source: "getsign.io",
    keywords: ["otp", "one-time password", "authentication", "passcode", "security", "enforce passcode", "secure delivery", "recipient", "email verification", "monday.com", "sign", "expiration", "spam"],
    body: `OTP (One-Time Password) authentication requires recipients to enter a time-limited code sent by email before they can access and sign a document. Step 1 - Prepare the document: select your board and item, upload or create a template in the drag-and-drop editor, add fields (text, signature, date), and save. Step 2 - Activate OTP: open Settings/Security in the GetSign view, enable the OTP option ("OTP - Secure your documents delivery"), turn on "Enforce Passcode", and confirm the recipient's email. Step 3 - Send: review sender details and click Send; GetSign emails the OTP passcode when the recipient tries to open the document. Step 4 - Recipient access: the recipient clicks the link, receives a separate email with the passcode, and enters it to unlock and sign. The passcode is unique per session/recipient, single-use, with a configurable expiration window. OTP works on desktop and mobile and is included at no additional charge. If a recipient doesn't receive the OTP, they can request a resend; check spam and verify the email address.`,
  },
  {
    title: "Add custom email branding (logo) to eSignature invites",
    url: "https://getsign.io/getting-started/esignature-invites-with-custom-email-branding/",
    source: "getsign.io",
    keywords: ["custom email branding", "logo", "business logo", "png", "jpeg", "svg", "workspace", "sender name", "sender email", "esignature invite", "settings", "branding", "monday.com"],
    body: `You can add your business logo to eSignature invite emails. Access the feature: open your board, select the relevant item, locate the GetSign view in the item's details (typically at the bottom), and find the Settings/Branding options. Add your logo: in the "Add Your Business Logo" area, drag and drop your logo file into the upload area and click Save; preview the branded email and adjust size as needed. Send: verify the Sender Name and Sender Email in Settings, confirm your email for deliverability, then click Send (or Copy Link to share elsewhere). Supported logo formats: PNG, JPEG, SVG. Each workspace supports one logo, changeable at any time; emails are responsive on all devices. Limitations: only the logo is customizable — custom footers or taglines are not supported; you cannot currently upload different logos for different boards or teams; email verification is required to avoid spam filters.`,
  },
  {
    title: "Generate quotes and invoices from monday.com board data",
    url: "https://getsign.io/capabilities/quotes-and-invoices/",
    source: "getsign.io",
    keywords: ["quotes", "invoices", "template", "subitems", "pricing", "tax calculation", "subtotals", "payment links", "esignature", "pdf export", "batch signing", "signing order", "gdpr", "hipaa", "monday.com"],
    body: `GetSign generates quotes and invoices from monday.com board data. To create one: select items containing pricing/customer/deal info; choose a template (quote, invoice, or custom); configure which subitem columns to display (product name, quantity, unit price, discount); send via email or share a link; and track progress in real time from your board. Documents auto-fill with pricing, product, and contact data, and automatically include tax calculations, subtotals, and totals. They support eSignature fields and payment links, custom branding (logo, colors, layout), and can be exported to PDF or sent directly from the board. Signatures are legally binding and GDPR/HIPAA compliant, each with a legal audit trail; OTP verification is available before signing. Additional features: batch signing, template gallery with auto-fill, custom email branding, public signing links, signing-order control, and real-time status monitoring.`,
  },
  {
    title: "GetSign Send: generate and share signing links",
    url: "https://getsign.io/capabilities/getsign-send/",
    source: "getsign.io",
    keywords: ["getsign send", "signing link", "status column", "automation trigger", "public link", "encrypted", "audit log", "real-time tracking", "multiple recipients", "otp", "signing order", "gdpr", "hipaa", "monday.com"],
    body: `GetSign Send generates encrypted signing links from monday.com items. Upload an existing document or create one within an item. To trigger the link, update the item's status column (e.g., to "Send Document") as configured in automation settings; GetSign generates the signing link on the status change. Sharing: copy and share the link directly (no email required), or via email, embedded forms, chat, or websites. Each link is encrypted, tracked, and tied to audit logs. Tracking: real-time updates show who signed, when, and who's pending; the board reflects status automatically with a full audit trail. Capabilities: works with multiple recipients and large campaigns; compatible with OTP verification, signing order, and custom email branding; public link sharing removes the login requirement; automation triggers remove manual send steps. GDPR and HIPAA compliant.`,
  },
  {
    title: "Sign Anywhere: signing without predefined fields",
    url: "https://getsign.io/capabilities/sign-anywhere/",
    source: "getsign.io",
    keywords: ["sign anywhere", "signature fields", "single-signer", "pdf", "docx", "template gallery", "files column", "audit log", "timestamps", "identity verification", "no setup", "monday.com"],
    body: `Sign Anywhere lets recipients sign a document without predefined signature fields. The process: upload or attach a document (from your board's Files column or the Template Gallery); enable Sign Anywhere and send the document as-is, skipping the step of adding signature fields; the recipient taps anywhere on the document to place their signature, initials, or sign date; completion is tracked. Key characteristics: no predefined fields required, so recipients can sign anywhere without preset placement; works with any PDF or DOCX uploaded to your board; optimized for single-signer documents with no predefined signing location; every action is tracked with full audit logs, timestamps, and identity verification, and the signed file is saved to your board. Sign Anywhere is included in GetSign's capabilities at no additional payment.`,
  },
  {
    title: "Custom email branding for signature requests",
    url: "https://getsign.io/capabilities/custom-email-branding/",
    source: "getsign.io",
    keywords: ["custom email branding", "sender name", "reply address", "reply-to", "logo", "brand color", "personalized message", "batch", "signature request", "settings", "monday.com"],
    body: `Custom Email Branding personalizes the signature-request emails sent through GetSign. Customizable elements: sender identity (sender name and reply address), visual branding (logo upload and brand color), and custom messaging (personalized content in outbound emails). Setup: select your board and the relevant item for eSignature; upload your custom logo; send the branded invite (or share the signing link); monitor progress via real-time status on your board. It operates entirely within monday.com with no external tools and does not alter the secure signing workflow. Supports display-name and reply-to customization, logo embedding, brand color, and batch application across multiple signature requests. Included in standard GetSign capabilities at no additional cost. No specific character limits or advanced options are stated.`,
  },
  {
    title: "GetSign Track: monitor signature status and audit logs",
    url: "https://getsign.io/capabilities/getsign-track/",
    source: "getsign.io",
    keywords: ["getsign track", "tracking", "signature status", "sent", "viewed", "signed", "pending", "audit trail", "timestamped logs", "cancel request", "export logs", "activity feed", "monday.com", "compliance"],
    body: `GetSign Track logs every signature event within monday.com boards, showing document progress from send to final signature with timestamps. View each recipient's status as sent, viewed, signed, or pending. Features: timestamped logs for every send and signer, a full audit trail for compliance, a live activity feed per document, and multi-party signature tracking. Controls: cancel an active signature request instantly from the board without a document reset; audit logs are exportable per document to share with internal teams, legal, or external stakeholders. GetSign Track requires no separate setup and is included with all GetSign workflows (batch signing, document links, custom email branding). It operates entirely within monday.com with no external integrations.`,
  },
  {
    title: "Display multiple images in GetSign document templates",
    url: "https://getsign.io/how-tos/display-multiple-images-in-document-templates-with-getsign/",
    source: "getsign.io",
    keywords: ["multiple images", "document template", "file column", "image grid", "rows and columns", "template editor", "drag and drop", "resize", "variable image count", "blank slots", "getsign"],
    body: `GetSign can display multiple images from a single monday.com file column inside a document template, with a configurable grid layout. Setup: (1) Open GetSign and create a new template. (2) In the editor, locate the file column that contains your images and drag it into the template. (3) Configure the image block by setting the number of columns and rows, then resize the block to fit your design. (4) Preview and adjust until it matches your design. Image fields can be positioned via drag-and-drop. The feature handles variable image counts: if a board item contains fewer images than the grid is configured to show, unused grid spaces display as blank rather than causing an error, so one template works across items with different numbers of images.`,
  },
  {
    title: "Editing GetSign templates: gallery-level vs item-level changes",
    url: "https://getsign.io/how-tos/new-document-template-editing-ui/",
    source: "getsign.io",
    keywords: ["edit template", "gallery level", "item level", "template library", "global changes", "individual document", "continue editing", "warning", "shared template", "template editor", "duplicate template", "getsign"],
    body: `GetSign offers two editing scopes, each with a confirmation warning. Global (gallery-level) changes: open the Gallery/Template Library, locate the template, and click Settings/Edit (gear or ellipsis). A warning states that editing a shared template from the gallery applies changes to ALL items. Click Continue Editing to proceed, or Cancel. These changes affect all existing and future documents using that template. Individual (item-level) changes: go to the specific item containing the document, find the GetSign section (Share/Document), and click Edit. A warning states changes apply only to THIS item. Click Continue Editing. These changes affect only that single document. Best practices: read the warnings before confirming, distinguish gallery-level (global) from item-level, cancel if unsure, duplicate a template before major global changes as a backup, and communicate the distinction to your team.`,
  },
  {
    title: "Import Excel/CSV data into monday.com and use it with GetSign",
    url: "https://getsign.io/how-tos/import-excel-data-into-monday-com/",
    source: "getsign.io",
    keywords: ["import excel", "csv import", "import items", "column mapping", "item name", "subitems", "xlsx", "signature link", "data sync", "board columns", "getsign", "monday.com"],
    body: `Prepare your spreadsheet first: remove duplicates, ensure consistent column headers, decide which columns become subitems or connected fields, and save as .xlsx or .csv. Import steps: (1) Open your board and click the arrow next to the New Item button. (2) Select Import Items. (3) Drag or browse to select your Excel/CSV file. (4) Designate which Excel column is the main Item Name. (5) Match each additional column to the corresponding monday.com column type (Email, Date, Status) — unmapped columns are not imported. Using GetSign with imported data: ensure GetSign is installed, open an imported item and access the GetSign tab, map board fields into your template, and send for signature via secure link. Status updates and signature history sync automatically. Use cases: onboarding, sales pipeline/lead tracking, inventory/supplier management, project timelines.`,
  },
  {
    title: "Automate eSignature document workflows in GetSign",
    url: "https://getsign.io/how-tos/automate-esignature-workflow/",
    source: "getsign.io",
    keywords: ["esignature workflow", "automation", "status change trigger", "autosend", "bulk send", "data mapping", "document template", "live item data", "gdpr", "hipaa", "integration", "getsign", "monday.com"],
    body: `GetSign automates eSignature workflows on monday.com: choose a workflow, upload a document, automatically pull data from board columns, automate dispatch, add the GetSign integration, and send with automation. Core behavior: documents trigger automatically when a status changes, fields populate with live item data, and completed files are stored on your board. Dynamic field linking works with text, status, email, date, and other board columns. Batch operations: select multiple items and trigger AutoSend via a bulk status change, sending multiple documents to multiple recipients at once. Multi-workflow support: each workflow instance can have its own template, trigger, and logic. Security/compliance: signatures are secure, timestamped, and audit-ready, compliant with GDPR and HIPAA.`,
  },
  {
    title: "GetSign updates: AI field detection, sender setup, audit-log display, column creation, upload signature",
    url: "https://getsign.io/how-tos/new-getsign-updates-ai-fields-sender-setup/",
    source: "getsign.io",
    keywords: ["ai field detection", "sender name", "sender email", "audit log", "audit trail", "create column", "upload signature", "template editor", "signer email", "png jpeg", "getsign", "monday.com"],
    body: `AI-powered field detection: upload a document (e.g., a PDF contract); the AI scans it and suggests form field placements. Review the detected fields, assign each to its monday.com column (e.g., an email field to the Signer Email column), and double-check placement before saving. Simplified sender setup: in GetSign app settings enter a Sender Name and Sender Email and click Save — documents can be sent immediately without email verification. Audit-trail display control: in settings, find the option to display the audit log on the document and toggle it Off; the full audit trail remains accessible within GetSign settings even when removed from the final document. Direct column creation: while editing a template, drag a new field and in the column selector choose Create a new column; it's added to your board instantly (appears empty in GetSign until filled). Upload signature: when signing, click a signature field, choose Upload, and select a high-resolution saved signature file (PNG/JPEG).`,
  },
  {
    title: "Set up the GetSign Form Filler on monday.com",
    url: "https://getsign.io/how-tos/automate-data-collection-in-monday-com-with-getsign-form-filler/",
    source: "getsign.io",
    keywords: ["form filler", "data collection", "item view", "field linking", "text box", "date picker", "signature", "edit form", "reorder fields", "share send", "logo branding", "board columns", "getsign", "monday.com"],
    body: `Set up GetSign Form Filler to collect data into monday.com: (1) On your board, click an item and select GetSign to create a new Item View. (2) Choose an existing template or create one by dragging field types such as Text Box, Date Picker, and Signature. (3) Link each form field to a monday.com column (select existing or create new within field configuration). (4) Click Save to preserve the basic structure. (5) Click Edit Form in the Item View to customize presentation. (6) Customize the form title, add instructions/descriptions, optionally upload a logo. (7) Use the right-side field list to reorder fields by dragging; select individual fields or Select All for batch arrangement. (8) Click Save and any Apply buttons to finalize. (9) From the Item View, click Share then Send to email recipients. Notes: ensure fields are correctly linked to columns for automated data transfer, use descriptive labels, and test the workflow with your own email before deployment. Submitted data auto-populates your board.`,
  },
  {
    title: "Enable Auto Sign Anywhere in GetSign on monday.com",
    url: "https://getsign.io/how-tos/enable-auto-sign-anywhere-on-monday-com/",
    source: "getsign.io",
    keywords: ["auto sign anywhere", "sign documents", "status column", "email column", "files column", "add view", "email verification", "signing link", "integration center", "automation", "column mapping", "getsign", "monday.com"],
    body: `Prerequisites: create three board columns — a Status column (tracks progress and automates dispatch), an Email column (recipient addresses), and a Files column (documents to sign). Steps: (1) Open an item, click + Add View, and select GetSign then Sign Documents (only the Sign Documents workflow supports Auto Sign Anywhere). (2) Upload your document in the GetSign tab, map the columns created above, check Enable Auto Sign Anywhere, select the email column for recipient mapping, and Save. (3) Verify your email: a verification email is sent; click the confirmation link before sending. (4) Click Send; recipients get an email with a signing link and can tap/click anywhere on the document to sign. (5) To automate future sends, configure an automation in the Integration Center: When status changes to [X], send GetSign document for eSign. Options: preview before sending, download after signing, and receive real-time board status updates on signature.`,
  },
  {
    title: "Generate quotes and invoices with line items on monday.com",
    url: "https://getsign.io/how-tos/generate-quotes-and-invoices-on-monday-com/",
    source: "getsign.io",
    keywords: ["quotes", "invoices", "getsign generate", "line items", "subitems", "pdf docx", "totals and taxes", "template", "status tracking", "eidas esign", "configure line item", "monday.com"],
    body: `Generate quotes and invoices in GetSign: (1) Install GetSign and open an item view. (2) Click Upload a New Template to add an invoice/quote in PDF or DOCX, or create one within GetSign; map relevant board columns (email, files, status) for real-time updates. (3) Toggle on GetSign Generate. (4) Configure line items: drag the Line Items field to the template, then tap Configure Line Item to select which subitem columns display (product name, quantity, unit price, discount). Subitems act as detailed line items with automatic totals and taxes. (5) Review fields and signature requirements, then Send via email or copy the sharing link; recipients can view, sign, and approve immediately, and status updates automatically. Capabilities: automatic calculations for totals, taxes, and credits; reusable templates; real-time status tracking (sent, viewed, signed, completed); compliance with eIDAS, ESIGN, UETA, GDPR, and HIPAA.`,
  },
  {
    title: "Collect payments with Stripe on monday.com using GetSign",
    url: "https://getsign.io/how-tos/collect-payments-with-stripe-on-monday-com/",
    source: "getsign.io",
    keywords: ["stripe", "payments", "payment item field", "signing link", "checkout", "invoice", "contract", "status column", "currency", "digital wallets", "automation", "getsign", "monday.com"],
    body: `GetSign combines payment collection and document signing in one workflow via Stripe. Step 1 - Access the GetSign item view: open your board, select the item, click the GetSign view. Step 2 - Connect Stripe: in the GetSign Settings section, activate the Stripe payment option and link your Stripe account. Step 3 - Configure status and label: assign a status column and label (e.g., Payment Required) that triggers the payment process and updates the board once payment completes. Step 4 - Add the payment item field: click Prepare to open the signature builder, drag the Payment Item field to the document, set the amount and currency (USD, EUR, etc.), and save. Step 5 - Send: confirm sender name and email, click Send to email the document and payment link, or copy the signing link; recipients sign, then complete Stripe checkout. Notes: Stripe supports credit cards, debit cards, and digital wallets depending on account settings; if checkout doesn't complete, payment status fails but the signature still processes; works with monday.com automations for post-payment actions.`,
  },
  {
    title: "Automate PDF forms in monday.com using GetSign",
    url: "https://getsign.io/how-tos/how-to-automate-pdf-forms-in-monday-com/",
    source: "getsign.io",
    keywords: ["pdf forms", "form automation", "auto-detect fields", "form filler", "w-9", "w-8ben", "i-9", "compliance", "tax forms", "hr documents", "board columns", "status change", "getsign", "monday.com"],
    body: `GetSign automates PDF-based workflows (tax forms, HR documentation, compliance) inside monday.com. Step 1 - Auto-detect PDF form fields: upload an existing PDF form (W-9, rental application, etc.); GetSign automatically scans and detects all fillable fields, and can generate all required fields in one click, handling complex multi-page forms without manual configuration. Step 2 - Enable the guided Form Filler: in GetSign Settings enable Form Filler, click edit on your form template and create the Form Filler version, customize title/branding, insert all detected fields in one click, and arrange them in logical order so fields appear in a clean flow rather than navigating a PDF manually. Integration: trigger form sending on monday.com status changes, pre-fill from existing board columns, track completion within the item, and store finalized documents. Use cases: W-9/W-8BEN from contractors, I-9 for new hires, rental/lease applications, loan applications, insurance claims, compliance docs.`,
  },
  {
    title: "Digitize printable forms on monday.com (automatic field detection)",
    url: "https://getsign.io/how-tos/digitizing-printable-forms-on-monday-com/",
    source: "getsign.io",
    keywords: ["digitize forms", "form field detection", "migrate fields", "pdf editor", "checkboxes", "text boxes", "required fields", "assign signers", "column mapping", "templates", "getsign", "monday.com"],
    body: `GetSign's Automatic Form Field Detection digitizes PDF forms by recognizing and placing fields (text boxes, checkboxes, date fields) in one click, eliminating manual placement. Step 1 - Upload the template: in GetSign, upload the document template; it opens in the editor. Step 2 - Automatic detection: the editor recognizes form fields across the document (text boxes, checkboxes). Step 3 - Migrate fields: click the Migrate Fields button; GetSign positions all detected fields into the document within seconds. Step 4 - Review and adjust: review each field, mark fields as required when needed, edit text or adjust placement, assign fields to specific signers, and map fields to existing monday.com columns or create new columns from the editor. Step 5 - Save and send: save changes and send for signature directly from GetSign. Benefits: eliminates manual placement, reduces setup errors, standardizes templates, and accelerates signing.`,
  },
  {
    title: "Delete webhooks on monday.com created by GetSign",
    url: "https://getsign.io/how-tos/delete-webhooks-on-monday-com-created-by-getsign/",
    source: "getsign.io",
    keywords: ["webhooks", "delete webhook", "automation id", "jetpack apps", "support form", "contact", "account url", "technical issue", "manage automations", "getsign", "monday.com"],
    body: `GetSign webhooks cannot be deleted directly through monday.com's standard automation interface due to platform limitations, so deletion is handled via a support request. Step 1 - Locate the webhook automation ID: go to your board's Automations section, click Manage (top right), find the GetSign webhook automation, click the three horizontal dots next to it, and select Copy automation ID. Step 2 - Access Jetpack Apps support: visit the GetSign website and click Contact to open the support form. Step 3 - Submit the request: complete the form with your full name, the email associated with your monday.com account, and your exact monday.com account URL (e.g., yourcompanyname.monday.com). Set Type of Inquiry to Technical Issue, Product to GetSign, Subject to Delete Webhook. In the Message field paste the copied Automation ID and any context. Select Account Type (Paid or Free), then Submit. Note: your exact monday.com account URL is critical for locating your account and processing the request.`,
  },
  {
    title: "Generate a document signing link with GetSign (single signer)",
    url: "https://getsign.io/how-tos/generate-a-document-signing-link/",
    source: "getsign.io",
    keywords: ["signing link", "generate link", "single signer", "share button", "status column", "url column", "edit template", "signature field", "automation", "item view", "getsign", "monday.com"],
    body: `GetSign creates unique URLs that let signers complete documents without email threads or logins. Links work best for single-signer scenarios and can be shared via email, WhatsApp, Slack, or SMS; sessions are encrypted with access logging, and signatures track in real time. Step 1 - Board setup: install GetSign, upload a template (PDF or DOCX), and create a Status column (e.g., Generate Link) and a URL/link column (e.g., Signing Link). Step 2 - Template prep: open GetSign in Item View and preview; if a signature field is missing, click Edit Template, drag the signature field, then Save and close. Step 3 - Manual generation: in Item View click Share, select Generate Link; the URL saves to the Signing Link column. Step 4 - Automated (optional): in Settings select the status column that triggers automation, set the trigger value (e.g., Done), and choose the column for storing the link, then save. Step 5 - Track status: view who signed, timestamps, and download from the File column. Limitation: each signing link supports only one signer per document; multiple signers require separate links.`,
  },
  {
    title: "Generate multi-signer signing links on monday.com",
    url: "https://getsign.io/how-tos/generate-multi-signer-links-on-monday-com/",
    source: "getsign.io",
    keywords: ["multi-signer", "signing links", "signer roles", "email column", "share and track", "otp", "email validation", "status column", "link column", "template", "one-time password", "getsign", "monday.com"],
    body: `GetSign automates creation of shareable signing links for documents requiring multiple signatures. Step 1 - Prepare the template: in GetSign settings, open or create a template, assign distinct roles for each signer (e.g., Client Manager, Client Legal), map one role to a specific team member and another to an Email column, optionally assign form fields to signer roles, then save. Step 2 - Activate link generation: open GetSign app settings, scroll to Share and Track, and toggle it on. Step 3 - Select trigger column and value: choose a Status column to trigger generation, select a status value (e.g., Generate Link), and select or create a Link column. Step 4 - Configure email validation: in Share & Track, find the Email Validation toggle — Off for direct link access without verification, On to require signers assigned to an email column to enter a One-Time Password (OTP). Save. Step 5 - Trigger: create/update a board item, ensure email columns have correct addresses, and change the Status column to the trigger value. Best practices: test all roles and fields before deploying, keep email data accurate, enable OTP for sensitive documents, and inform signers they receive one link and must select their role on opening.`,
  },
  {
    title: "Enhanced AcroFields assignment options for uploaded PDF templates",
    url: "https://getsign.io/how-tos/enhanced-acrofields-assignment-options/",
    source: "getsign.io",
    keywords: ["acrofields", "pdf templates", "field detection", "default assignee", "multi-signer", "person column", "email address", "reassign fields", "form fields", "checkboxes", "compliance templates", "getsign"],
    body: `GetSign's AcroFields feature automatically detects form fields (text inputs, checkboxes) in uploaded PDF templates, eliminating manual drag-and-drop for complex forms. Previously all detected fields defaulted to the person setting up the document, requiring manual reassignment for multi-signer workflows. This update lets users assign detected fields to any signer by default, not just the uploader. How it works: (1) Upload a PDF containing AcroFields. (2) GetSign automatically detects all supported fields. (3) Select a default assignee (a board person-column value or an email address). (4) All fields assign accordingly. (5) Individually override and reassign fields as needed. Benefits: reduces setup time for multi-signer workflows; streamlines government forms, vendor forms, HR documents, and compliance templates; maintains flexibility for custom assignments.`,
  },
  {
    title: "Select specific sub-item columns for PDF templates",
    url: "https://getsign.io/how-tos/select-specific-sub-item-columns-for-pdf-templates/",
    source: "getsign.io",
    keywords: ["sub-items", "pdf templates", "sub-item columns", "checkboxes", "filters", "invoices", "quotes", "procurement", "column selection", "document generation", "getsign", "monday.com"],
    body: `This feature lets you control which sub-item columns appear in PDF templates instead of automatically including all columns. Steps: (1) Open your GetSign PDF template. (2) Drag the Sub-items element onto the template. (3) In the right-side configuration panel, locate the sub-item columns list. (4) Use checkboxes to select only the desired columns. (5) Optionally apply existing filters to control which sub-items display. (6) Save the template. Only selected columns appear in generated documents. Use cases: for invoices/quotes, display product, quantity, and price while excluding internal cost or margin data; for project task breakdowns, show task name and due date only; for procurement, present vendor-facing fields while omitting internal approval info. This enables cleaner, more focused PDF generation by eliminating internal tracking columns.`,
  },
  {
    title: "Add digital signatures to PDFs on monday.com (uploaded, stored, and generated documents)",
    url: "https://getsign.io/how-tos/add-digital-signature-in-pdf-on-monday-com/",
    source: "getsign.io",
    keywords: ["digital signature", "pdf", "uploaded template", "stored documents", "generated documents", "send for signature", "signers", "signature fields", "cryptographic signature", "esignature", "getsign", "monday.com"],
    body: `Digital signature support in GetSign covers uploaded templates and stored documents in addition to generated documents, so cryptographically secure signatures can be applied regardless of how a document was created (expanded as of November 27, 2025). For uploaded templates: upload the PDF as a template, place signature fields, assign signers, enable the Digital Signature option, then send for signing. For stored documents: upload your file through Store Documents, select Send for Signature, place fields and assign signers, enable Digital Signature, then send. For generated documents: the existing workflow is unchanged — enable digital signatures when configuring your signing settings. In each workflow, enabling the Digital Signature toggle is the step that applies the secure signature to the document before it is sent to signers.`,
  },
  {
    title: "Let signers download documents before signing",
    url: "https://getsign.io/how-tos/download-documents-before-signing-on-monday-com/",
    source: "getsign.io",
    keywords: ["download document", "before signing", "signer", "signing link", "download button", "get started", "template gallery", "offline review", "esignature", "getsign", "monday.com"],
    body: `GetSign allows signers to download a document at any point before signing. Previously this was only available for documents generated within GetSign; it now works for documents accessed through the Template Gallery. There are two ways a signer can download: From the top navigation bar — the signer opens the signing link, locates the Download button in the top-right corner, and clicks it to save the document for offline review. From the opening dialog — when the document loads, a dialog appears and the signer finds the Download option beneath the Get Started button, clicks to download, and returns to sign when ready. Downloading is available before and alongside signing, so signers can review or print and come back to complete signing. Use cases: reviewing legal contracts, printing HR documents, assessing vendor agreements, reviewing proposals offline.`,
  },
  {
    title: "Send GetSign emails from a custom domain (DNS/DKIM setup)",
    url: "https://getsign.io/how-tos/send-email-from-custom-domain-on-monday-com/",
    source: "getsign.io",
    keywords: ["custom domain", "email", "getsign send", "dns records", "cname", "dkim", "custom mail from", "domain verification", "sender name", "deliverability", "propagation", "monday.com"],
    body: `Configure GetSign to send emails from your own domain. Step 1 - Add root domain: in GetSign Send, go to Domain Configuration in settings, enter your root domain (e.g., yourcompany.com), and select Begin Domain Verification. Step 2 - Add DNS records: GetSign provides CNAME records to copy into your DNS provider; these set up DKIM Authentication (secure delivery) and Custom Mail From (so emails display your domain). Add the records through your DNS provider (GoDaddy, Namecheap, cPanel, Cloudflare, Squarespace, Wix, Bluehost, AWS Route 53, Google Cloud DNS, DigitalOcean). DNS can take up to 24-48 hours to propagate, though often faster. Step 3 - Verify: return to GetSign, check the confirmation box, and click Verify; green checkmarks indicate success. Step 4 - Configure sender details: in GetSign Send, enter your sender name and email using the verified domain (e.g., hello@yourcompany.com), and optionally set email language. All subsequent emails then send from your custom domain, improving brand consistency and deliverability.`,
  },
  {
    title: "Send documents without requiring signatures",
    url: "https://getsign.io/how-tos/sending-documents-without-requiring-signatures-in-getsign/",
    source: "getsign.io",
    keywords: ["send without signature", "document sharing", "share tab", "send to", "request signatures from", "email content", "generated document", "signed copy", "no signature field", "distribution", "getsign", "monday.com"],
    body: `GetSign previously required at least one signature field to send a document; that requirement has been removed, so you can share documents for review, reference, or distribution without collecting signatures. This supports three scenarios: direct document sharing (upload and send files such as reports without signatures), generated document distribution (send documents auto-generated from monday.com data without signature collection), and signed copy distribution (send completed signed documents to non-signers such as supervisors or auditors). To send without signatures: open your document in the GetSign app, go to the Share tab and the Send To section, and enter the recipient's email. Recipients who need to sign appear under "Request signatures from", while non-signature recipients simply receive the document. Optionally add a custom message in the Email Content box, then click Send. The recipient receives the document without being prompted to sign.`,
  },
  {
    title: "Batch sign documents on monday.com using GetSign AutoSend",
    url: "https://getsign.io/how-tos/batch-sign-on-monday-com-using-getsign/",
    source: "getsign.io",
    keywords: ["batch sign", "autosend", "status label", "email delivery", "bulk send", "signature request", "board items", "trigger", "multiple recipients", "status column", "getsign", "monday.com"],
    body: `GetSign supports batch sending of signature requests using a status-label trigger called AutoSend. Step 1 - Prepare your board: create a board where each item (row) is a document and includes fields such as name, email, and the file to sign. Step 2 - Create the AutoSend status label: open the board's status column, add a new label named AutoSend (or similar), and click Apply (you can reuse an existing label). Step 3 - Enable AutoSend: go to GetSign Send - Email Delivery configuration, turn on the AutoSend feature, select the status label that triggers sending, and save. Step 4 - Execute batch send: select multiple items and bulk-update their status to AutoSend; GetSign processes the documents and sends them to the listed email addresses. Each item must include a valid email address and an uploaded document file; missing information prevents sending. Additional capabilities: multi-page signing with customizable rules, sending one document to multiple recipients, and assigning multiple signature fields.`,
  },
  {
    title: "Cast a formula column value to text for signing",
    url: "https://getsign.io/how-tos/casting-formula-value-to-a-text-value/",
    source: "getsign.io",
    keywords: ["formula", "cast to text", "formula column", "static value", "document template", "review and sign", "esignature", "calculated value", "formula field", "getsign", "monday.com"],
    body: `GetSign lets you display a monday.com formula column's calculated value as static text within a document for eSignature, presenting a defined result instead of a dynamic formula column and locking the value so it cannot change before signing. Prerequisites: a board with formula columns set up for calculations, the GetSign app installed, and an active document template. Step 1 - Access document editing: navigate to your item and open the GetSign tab. Step 2 - Add the formula field: select the formula field from the available options, place it where needed, add any other required fields, and click SAVE. Step 3 - View in recipient email: when recipients click Review & Sign, the formula field displays the calculated value. The formula field appears as a populated value in the final document the recipient views and signs, effectively converting the dynamic formula into a displayable text element.`,
  },
  {
    title: "Create PDF fillable forms on monday.com (text, signature, checkbox, dropdown, date fields)",
    url: "https://getsign.io/how-tos/create-pdf-fillable-forms-on-monday-com/",
    source: "getsign.io",
    keywords: ["fillable forms", "pdf", "template", "text box", "signature", "checkbox", "dropdown", "date field", "column mapping", "secure link", "audit trail", "docx", "required field", "getsign", "monday.com"],
    body: `Create fillable forms in GetSign that sync responses back to your board. Step 1 - Upload document: open the GetSign app view, select Upload a New Template, upload a supported file (PDF, DOCX, or DOC), and click Next to open the document editor. Step 2 - Add form fields: in the editor, drag and drop Text Box, Signature, Checkbox, Dropdown, or Date fields and position them over the corresponding areas of the form. Step 3 - Map fields to board columns: click each field to open its settings and assign it to an existing board column (email, phone, department, etc.); you can create new columns directly from the mapping window. Entered data automatically populates the mapped columns. Step 4 - Save and send: click Save to finalize the template, then Send to deliver the form via a secure link. Step 5 - Monitor responses: in your board, see which recipients completed the form, view timestamps, and retrieve signed documents stored in the File column. Forms are mobile-friendly, templates are reusable, and signed documents include audit trails with timestamps.`,
  },
  {
    title: "New GetSign features: subitems, signing-link expiry, template tools, gallery search, member access",
    url: "https://getsign.io/how-tos/new-getsign-features-to-power-your-document-workflows-in-monday-com/",
    source: "getsign.io",
    keywords: ["new features", "subitems", "signing link expiry", "template editing", "global edit", "item-level edit", "template gallery search", "board member access", "document workflow", "template toggle", "getsign", "monday.com"],
    body: `GetSign added several capabilities for monday.com document workflows. Subitems support: GetSign now works with subitems for workflows such as onboarding checklists, line-item quotes, and approval modules inside tasks; you can send for signature or generate using subitem data. Signing-link expiry: set an expiration date when sending a signing link — once expired, signatories can no longer access the document; you can reset and send fresh requests, with or without a new expiry. Template editing options: make global edits via the Templates section in settings to change a template for all future uses, or item-level edits using the edit icon within an item to change the template only for that case. Template gallery search: a search bar lets you find templates by keyword instantly. Board member template access: by default only board owners access the template gallery, but a toggle now lets board members access templates directly from the item view. Support contact: appsupport@jetpackwork.com.`,
  },
  {
    title: "New GetSign updates (June 2025): redesigned interface and features",
    url: "https://getsign.io/how-tos/new-updates-in-getsign-june-2025/",
    source: "getsign.io",
    keywords: ["june 2025 update", "redesign", "templates", "docx", "pdf", "signature fields", "document generation", "status trigger", "signing links", "payment collection", "email verification", "signature tracking", "template editor", "getsign"],
    body: `The redesigned GetSign replaces the previous workflow selection screen with five expandable sections: Templates and Documents upload, document generation via status triggers, sending documents for signature, signature tracking and storage, and signing link generation. Templates and Documents: upload DOCX or PDF, place signer fields by drag-and-drop, assign signature fields to persons or emails, and merge multiple templates. GetSign Generate: a status column acts as the trigger (no longer need monday.com's Automation Center); generated documents auto-save to a specified file column. GetSign Send: configure a status-based trigger, customize email subject and content; a one-time email verification is required. Signature Collection (tracking): monitor signing status via a status column, store signed copies in a file column, get automatic updates when documents are signed. GetSign Share & Track: generate unique signing links via a status trigger, store links in text columns, share via chat/CRM/SMS. Template editing: item-level edits (pencil icon) affect a single item; global edits apply across all items. Payment collection: the payment field is now in the template editor (configure amount, currency, instructions during signing).`,
  },
  {
    title: "Batch signing: send one document to many recipients",
    url: "https://getsign.io/capabilities/batch-sign/",
    source: "getsign.io",
    keywords: ["batch signing", "bulk send", "personalized links", "signing link", "automation center", "status trigger", "field mapping", "audit trail", "gdpr", "hipaa", "multiple recipients", "real-time tracking", "getsign", "monday.com"],
    body: `Batch Signing sends one document to many recipients at once, each with their own personalized signing link; the system generates an individual copy for each signer, so you do not upload duplicate documents. Workflow: (1) Select multiple board items that need the same document signed. (2) Ensure the template or file is pinned to each selected item. (3) Configure an automation in monday.com's Automation Center based on a status column change (e.g., "Send for Signature"). (4) Update the status to the configured label to automatically generate personalized signing links. (5) Monitor completion in real time via board status updates. Capabilities: each signer receives a unique, secure link; documents can use fields mapped from the board (name, department, pricing); signature status updates automatically; only a single document upload per item is needed regardless of recipient count; works with monday.com native automation triggers. Compliance: legal audit trail, GDPR and HIPAA compliant. Included with no separate add-on fee for existing subscribers.`,
  },
  {
    title: "GetSign Frequently Asked Questions",
    url: "https://getsign.io/frequently-asked-questions/",
    source: "getsign.io",
    keywords: ["faq", "free trial", "free plan", "document generation", "esignature", "board data", "sub-items", "audit log", "docx", "pdf", "stripe payments", "branding", "gdpr", "hipaa", "forms", "dropdowns"],
    body: `What is GetSign? A document automation and e-signature app for monday.com; generate documents from board data, send for secure signature, track progress, and store everything in the monday workflow. Free plan or trial? A 14-day free trial with full premium access; afterward a free plan with document generation and basic e-signature. Generate from board data? Yes, using board items and sub-items; insert dynamic tables, auto-fill fields, and filter sub-items by status, priority, or owner. Send for e-signature? Yes, to single or multiple signers with legally binding e-signatures; define signing sequence and add signing fields; activity is tracked on the board. Track status? Yes, real-time trail showing when documents are viewed, signed, or awaiting action, plus a full audit log. Upload templates and edit? Template gallery supports DOCX and PDF; DOCX is editable in the integrated editor with smart field insertion. Forms and payments? Build forms with text boxes, dropdowns, checkboxes; collect payments via Stripe during signature. Branding? Upload logos and personalize signing emails. Storage? Signed documents save automatically to the relevant item's files column. Security? Complies with GDPR, HIPAA, and global signature standards with data encryption.`,
  },
  {
    title: "How to send sales contracts for signature on monday.com",
    url: "https://getsign.io/send-sales-contracts-for-signature/",
    source: "getsign.io",
    keywords: ["sales contract", "esignature", "add new template", "signature collection", "email delivery", "verification", "signature field", "generate link", "copy link", "signed document storage", "contract template", "status tracking", "getsign"],
    body: `GetSign integrates with monday.com to send contracts and collect signatures without leaving the platform. Step 1 - Install and access: install GetSign from the marketplace, open the item view of your sales pipeline board, and click "Add New Template" to upload your contract file. Step 2 - Enable signature collection: toggle on "Signature Collection" and select the column where signed contracts will be stored (e.g., "Signed Contract File"). Step 3 - Configure email delivery: in the GetSign Email Delivery section, enter the sender name and email, then complete verification. Step 4 - Add signature placeholder: click "Edit" in the document section to open the editor, drag the Signature field to the desired location, then save and close. Step 5 - Send: click Send to email the contract, or use "Generate Link"/"Copy Link" for manual sharing; track status within the board. Step 6 - Automatic updates: once signed, the signed document is automatically uploaded to the designated column and the status updates. Features: email automation for delivery and reminders, real-time tracking, automatic file storage, reusable contract templates.`,
  },
  {
    title: "How to send rental agreements for signature on monday.com",
    url: "https://getsign.io/send-rental-agreement-for-signature-on-monday-com/",
    source: "getsign.io",
    keywords: ["rental agreement", "lease", "tenant", "landlord", "signature fields", "field mapping", "signer roles", "signing sequence", "getsign send", "trigger status", "bulk send", "signed pdf", "status tracking", "getsign"],
    body: `Step 1 - Create a board: set up columns for tenant name, property owner name, email addresses, property type, lease dates, and status tracking (sent, viewed, signed, failed). Step 2 - Upload and configure template: install GetSign and upload your rental agreement; configure signature fields by dragging tenant and landlord signature areas, mapping each to the corresponding email columns. Step 3 - Configure signature settings: enable e-signature collection and map signer roles (Tenant to Tenant Email, Landlord to Property Owner Email); select your status column for tracking. If multiple signers are required, GetSign enforces the signing sequence. Step 4 - Automate sending: use GetSign Send (Email Delivery) to set a trigger status such as "Send for Signature"; customize sender name, subject, message. When status updates, GetSign automatically emails both parties with secure signing links. Step 5 - Track signed agreements: set a trigger status such as "Signed" and map the signature link column to save URLs; signed PDFs store directly in the item. Step 6 - Bulk send: select multiple rows and update status to "Send for Signature"; filter by "Not Signed" to view pending agreements.`,
  },
  {
    title: "How digital signatures work on GetSign (certificates, compliance, plan availability)",
    url: "https://getsign.io/digital-signature-on-getsign/",
    source: "getsign.io",
    keywords: ["digital signature", "cryptographic certificate", "tamper detection", "audit log", "timestamp", "pdf certificate", "eidas", "esign act", "ueta", "hipaa", "external signers", "docx template", "plan availability", "getsign"],
    body: `GetSign uses cryptographic certificates to bind signatures to signer identity and document content; each signer's action is paired with an embedded certificate proving identity and intent. Secure signatures are generated automatically when documents are sent through monday.com, with no manual setup. Security architecture: (1) Encryption and certification — signatures include embedded digital certificates linking signers to their actions; (2) Tamper detection — any change to a signed document invalidates the digital certificate; (3) Audit logging — each signing action gets timestamp tracking and a complete audit trail. Technical capabilities: signed outputs are PDFs with embedded certificates and verification metadata; DOCX files are accepted as templates for generation; external signers do not need a GetSign or monday.com account and their sessions are tracked separately; signed PDFs open in standard readers to display certificate verification. Compliance cited: eIDAS AES (EU Regulation 910/2014), ESIGN Act (US), UETA (US state-level), and HIPAA. Plan availability: digital signature functionality is included in the Standard, Pro, and Enterprise plans only; Basic plan users must upgrade.`,
  },
];
