/**
 * Screenshot harness for the support manual (docs/manual/).
 *
 * Every image in the manual is generated by this script, so the manual can be
 * regenerated when the UI moves instead of rotting. Nothing here clicks a
 * control that writes: it logs in, navigates, switches tabs, and captures.
 *
 * Plain .mjs rather than .ts because tsx isn't installed locally — run it with
 * bare node, no --env-file needed (credentials come from the two env vars).
 *
 *   MANUAL_USER=… MANUAL_PASS=… node scripts/manual-shots.mjs
 *
 * Options via env:
 *   MANUAL_BASE     target origin (default: production console)
 *   MANUAL_REDACT   path to a JSON redaction map (see redact() below)
 *   MANUAL_THEME    "light" (default) or "dark"
 *   MANUAL_ONLY     comma-separated shot names, for iterating on one image
 *   MANUAL_VIEW     "general" captures the console as a general user sees it
 *                   (sets the jetta_view_as cookie, which is a real privilege
 *                   downgrade honoured by the APIs — not a UI trick) and
 *                   writes to docs/manual/images-general instead
 *
 * IMPORTANT: the redaction map holds real customer names, so it lives outside
 * the repo and is passed in by path. Never commit it.
 */
import { chromium } from "playwright";
import sharp from "sharp";
import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const BASE = process.env.MANUAL_BASE ?? "https://jettajetpack.vercel.app";
const USER = process.env.MANUAL_USER;
const PASS = process.env.MANUAL_PASS;
const THEME = process.env.MANUAL_THEME === "dark" ? "dark" : "light";
const ONLY = (process.env.MANUAL_ONLY ?? "").split(",").filter(Boolean);
const VIEW_AS = process.env.MANUAL_VIEW === "general" ? "general" : null;

const ROOT = path.resolve(import.meta.dirname, "..");
const RAW = path.join(ROOT, ".manual-raw"); // gitignored PNG staging
const OUT = path.join(ROOT, VIEW_AS ? "docs/manual/images-general" : "docs/manual/images");

/** Capture at 2x so the downscale to 1440 CSS px stays crisp. */
const VIEWPORT = { width: 1440, height: 900 };
const SCALE = 2;

/**
 * The shot list. `card` crops a single card by its title, which is what makes
 * close-ups legible — a full-page 1440px shot scaled into a document turns the
 * thing you're pointing at into mush.
 *
 *   route    where to go
 *   tab      visible text of a tab to click first
 *   card     card title to crop to (omit for a whole page)
 *   full     capture the entire scrollable page rather than the viewport
 */
const SHOTS = [
  { name: "login", route: "/login", anon: true, card: "Ops Console" },

  // Card titles below are taken from the live DOM, not from the docs — the two
  // have drifted ("Waiting on a human" is now "What needs you now", and the
  // briefing lives inside "Last 24 hours" rather than in a card of its own).
  { name: "today", route: "/today", full: true },
  { name: "today-last24", route: "/today", card: "Last 24 hours" },
  { name: "today-emerging", route: "/today", card: "Emerging issues" },
  { name: "today-needs-you", route: "/today", card: "What needs you now" },
  { name: "today-going-wrong", route: "/today", card: "What's going wrong" },
  { name: "today-would-help", route: "/today", card: "What would help" },
  { name: "today-documenting", route: "/today", card: "Worth documenting" },

  { name: "chats", route: "/chats", full: true },
  { name: "chats-transcript", route: "/chats", openFirstChat: true, full: true },
  { name: "chats-settings", route: "/chats/settings", full: true },
  { name: "chats-install", route: "/chats/install", full: true },

  { name: "evals", route: "/evals", full: true },
  { name: "evals-learnings", route: "/evals", tab: "Candidate learnings", full: true },
  { name: "evals-quality", route: "/evals", tab: "Draft quality", full: true },

  { name: "kb", route: "/kb", full: true },
  { name: "kb-review", route: "/kb", tab: "Review queue", full: true },

  // /analytics is one long page, not a tabbed one — crop the cards instead.
  { name: "analytics", route: "/analytics", full: true },
  { name: "analytics-daily", route: "/analytics", card: "Daily overview" },
  { name: "analytics-learning", route: "/analytics", card: "Learning & gap analytics" },
  { name: "analytics-runs", route: "/analytics", card: "Activity log (detailed runs)" },

  { name: "billing", route: "/billing", full: true },
  { name: "system", route: "/system", full: true },
  { name: "guide", route: "/guide", full: true },
  { name: "drafts", route: "/drafts", full: true },
];

/**
 * What a general user is actually shown: the nav gives them Today, Chats and
 * Guide, and /billing, /chats/settings and /chats/install redirect them away.
 * Capturing anything else would document a console they don't have.
 */
const GENERAL_SHOTS = new Set([
  "login",
  "today",
  "today-last24",
  "today-emerging",
  "today-needs-you",
  "today-going-wrong",
  "today-would-help",
  "today-documenting",
  "chats",
  "chats-transcript",
  "drafts",
]);

/** Stable fake cast — the same real person maps to the same fake one everywhere. */
const CAST = [
  ["Dana Whitfield", "dana.whitfield@northgate.example"],
  ["Marcus Reed", "m.reed@brightlane.example"],
  ["Priya Raman", "priya@casselton.example"],
  ["Tom Okafor", "tokafor@fieldstone.example"],
  ["Elena Vasquez", "elena.v@harborpoint.example"],
  ["Sam Lindqvist", "sam@quietriver.example"],
  ["Aisha Bello", "aisha.bello@larkfield.example"],
  ["Ben Fischer", "bfischer@westmere.example"],
];

function must(v, name) {
  if (!v) {
    console.error(`Missing ${name}. Usage:\n  MANUAL_USER=… MANUAL_PASS=… node scripts/manual-shots.mjs`);
    process.exit(1);
  }
  return v;
}

/**
 * Log in through the real endpoint and reuse the signed session cookie.
 *
 * Retried because the route writes an ops event to Redis after the password
 * check and doesn't guard that write — so a backend under strain fails the
 * *successful* login path while wrong passwords still return a clean 401.
 */
async function login(attempts = 4) {
  let last = "";
  for (let i = 1; i <= attempts; i++) {
    const res = await fetch(`${BASE}/api/auth/login`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ username: USER, password: PASS }),
    });
    if (res.status === 401) throw new Error("login rejected — check MANUAL_USER / MANUAL_PASS");
    const cookie = (res.headers.getSetCookie() ?? []).find((c) => c.startsWith("jetta_session="));
    if (res.ok && cookie) {
      if (i > 1) console.log(`  (login succeeded on attempt ${i})`);
      return cookie.split(";")[0].split("=").slice(1).join("=");
    }
    last = `${res.status} ${(await res.text()).slice(0, 120)}`;
    await new Promise((r) => setTimeout(r, 2_500));
  }
  throw new Error(`login failed after ${attempts} attempts: ${last}`);
}

/**
 * Swap real identities for the fake cast, in place, before the shutter.
 *
 * Blurred rectangles in a manual read as a leak patched after the fact;
 * consistent stand-in people read as the product. Emails and phone numbers go
 * by pattern. Names can't be pattern-matched, so they come from an explicit
 * map I fill in after reviewing a capture — anything still real is caught by
 * eye on review, not by hoping a regex covered it.
 */
function redact({ overrides, cast }) {
  const EMAIL = /[\w.+-]+@[\w-]+\.[\w.-]+/g;
  const PHONE = /\+?\d[\d\s().-]{8,}\d/g;

  // Deterministic pick so one real person is one fake person across every shot.
  const hash = (s) => {
    let h = 0;
    for (const ch of s) h = (h * 31 + ch.charCodeAt(0)) | 0;
    return Math.abs(h);
  };
  const fakeFor = (real) => cast[hash(real.toLowerCase()) % cast.length];

  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);

  for (const node of nodes) {
    let text = node.nodeValue;
    if (!text || !text.trim()) continue;
    const before = text;

    for (const [find, replace] of overrides) {
      if (find && text.includes(find)) text = text.split(find).join(replace);
    }
    text = text.replace(EMAIL, (m) => fakeFor(m)[1]);
    text = text.replace(PHONE, "+1 555 0100");

    if (text !== before) node.nodeValue = text;
  }

  // Avatars and gravatars can carry a face or an email hash.
  for (const img of document.querySelectorAll("img[src*='gravatar'], img[alt*='@']")) {
    img.style.filter = "grayscale(1) blur(6px)";
  }
}

/**
 * Refuse to photograph a broken page.
 *
 * A half-failed console still renders its shell, so a screenshot of an errored
 * card looks like a successful capture and would ship into the manual as if it
 * were the product. Anything matching these strings fails the shot instead.
 */
function pageErrors() {
  const SIGNS = [
    "This page couldn't load",
    "This page couldn’t load",
    "A server error occurred",
    "Unexpected end of JSON input",
    "Failed to execute 'json'",
    "Failed to fetch",
    "max requests limit exceeded",
  ];
  const text = document.body.innerText;
  return SIGNS.filter((s) => text.includes(s));
}

/**
 * Strip the admin-only chrome that "view as general" adds.
 *
 * The downgrade is real, but it also paints a warning banner and swaps the
 * topbar button for "Viewing as general — back to admin". A general user never
 * sees either, so leaving them in would document a console nobody has.
 * Matched on text because the banner has no stable hook, only Tailwind classes.
 */
function hideViewAsChrome() {
  for (const el of document.querySelectorAll("p, div")) {
    if (el.textContent?.startsWith("You are viewing the console as a")) el.remove();
  }
  for (const el of document.querySelectorAll("button, a")) {
    if (el.textContent?.includes("Viewing as general")) el.remove();
  }
}

/** Freeze anything that would make two runs differ for no reason. */
function settle() {
  for (const el of document.querySelectorAll("*")) {
    el.style.animationPlayState = "paused";
    el.style.transitionDuration = "0s";
  }
  // Blinking carets and "live" dots make diffs noisy.
  document.activeElement?.blur?.();
}

async function main() {
  must(USER, "MANUAL_USER");
  must(PASS, "MANUAL_PASS");

  const overrides = process.env.MANUAL_REDACT
    ? Object.entries(JSON.parse(await readFile(process.env.MANUAL_REDACT, "utf8")))
    : [];
  if (!overrides.length) {
    console.warn("! No MANUAL_REDACT map given — emails are masked, names are NOT. Review every image.");
  }

  await mkdir(RAW, { recursive: true });
  await mkdir(OUT, { recursive: true });

  const token = await login();
  const browser = await chromium.launch();
  const ctx = await browser.newContext({
    viewport: VIEWPORT,
    deviceScaleFactor: SCALE,
    colorScheme: THEME,
    reducedMotion: "reduce",
  });
  const origin = new URL(BASE);
  await ctx.addCookies([
    { name: "jetta_session", value: token, domain: origin.hostname, path: "/" },
    ...(VIEW_AS
      ? [{ name: "jetta_view_as", value: VIEW_AS, domain: origin.hostname, path: "/" }]
      : []),
  ]);
  if (VIEW_AS) console.log(`  (capturing as a ${VIEW_AS} user)`);
  // next-themes reads localStorage; without this the OS preference wins.
  await ctx.addInitScript((theme) => localStorage.setItem("theme", theme), THEME);

  const page = await ctx.newPage();
  // The signed-out shots need a context with no session cookie, or the gate
  // redirects /login straight to /today.
  const anonCtx = await browser.newContext({
    viewport: VIEWPORT,
    deviceScaleFactor: SCALE,
    colorScheme: THEME,
    reducedMotion: "reduce",
  });
  const anonPage = await anonCtx.newPage();

  let shots = VIEW_AS ? SHOTS.filter((s) => GENERAL_SHOTS.has(s.name)) : SHOTS;
  if (ONLY.length) shots = shots.filter((s) => ONLY.includes(s.name));
  const failed = [];

  const ATTEMPTS = 3;
  for (const shot of shots) {
    const page_ = shot.anon ? anonPage : page;
    let lastErr = null;
    for (let attempt = 1; attempt <= ATTEMPTS; attempt++) {
     try {
      await page_.goto(BASE + shot.route, { waitUntil: "domcontentloaded", timeout: 60_000 });
      // networkidle is unreliable on pages that poll; wait for content instead.
      await page_.waitForLoadState("networkidle", { timeout: 20_000 }).catch(() => {});
      // Skeleton placeholders photograph as grey bars — let them resolve.
      await page_
        .waitForFunction(() => !document.querySelector(".animate-pulse"), null, { timeout: 25_000 })
        .catch(() => {});
      await page_.waitForTimeout(1_200);

      if (shot.openFirstChat) {
        // /chats is an inbox: the transcript opens via ?c=<id> on the same
        // route, and rows are buttons calling router.replace — not links. Ask
        // the API which conversation exists rather than guessing at the DOM.
        const id = await page_.evaluate(async () => {
          const r = await fetch("/api/admin/chats?limit=20");
          const j = await r.json();
          const list = j.conversations ?? [];
          // Prefer one with a real exchange in it over an empty probe.
          return (list.find((c) => (c.messageCount ?? 0) > 1) ?? list[0])?.id ?? null;
        });
        if (!id) throw new Error("no conversations available to screenshot");
        await page_.goto(`${BASE}/chats?c=${id}`, { waitUntil: "domcontentloaded", timeout: 60_000 });
        await page_.waitForLoadState("networkidle", { timeout: 20_000 }).catch(() => {});
        await page_.waitForTimeout(2_000);
      }

      if (shot.tab) {
        await page_.getByText(shot.tab, { exact: false }).first().click();
        await page_.waitForTimeout(1_500);
      }

      const errs = await page_.evaluate(pageErrors);
      if (errs.length) throw new Error(`page error: "${errs[0]}"`);

      // MANUAL_DUMP writes each page's visible text out, so the redaction map
      // can be built by reading what's actually on screen instead of guessing.
      if (process.env.MANUAL_DUMP) {
        const text = await page_.evaluate(() => document.body.innerText);
        await writeFile(path.join(process.env.MANUAL_DUMP, `${shot.name}.txt`), text);
      }

      // The Next dev-tools badge floats over the bottom-left of every local page.
      await page_.addStyleTag({ content: "nextjs-portal{display:none!important}" }).catch(() => {});
      // One object: page.evaluate passes a single argument, so two params meant
      // `cast` arrived undefined and redaction threw the moment it hit an email.
      if (VIEW_AS) await page_.evaluate(hideViewAsChrome);
      await page_.evaluate(redact, { overrides, cast: CAST });
      await page_.evaluate(settle);

      // Substring, not exact: several titles carry a trailing count or date in
      // their text ("What needs you now6", "Daily overviewAug 15, 2026").
      const target = shot.card
        ? page_.locator(`[data-slot="card"]:has([data-slot="card-title"]:has-text("${shot.card}"))`).first()
        : page_;
      if (shot.card && (await target.count()) === 0) throw new Error(`card "${shot.card}" not found`);

      const raw = path.join(RAW, `${shot.name}.png`);
      await target.screenshot({ path: raw, ...(shot.card ? {} : { fullPage: shot.full ?? false }) });

      // Downscale 2x → 1x and compress. WebP because sips can't write it and
      // PNG at this size would blow the artifact budget.
      const meta = await sharp(raw).metadata();
      await sharp(raw)
        .resize({ width: Math.round(meta.width / SCALE) })
        .webp({ quality: 82 })
        .toFile(path.join(OUT, `${shot.name}.webp`));

      console.log(`✓ ${shot.name}${attempt > 1 ? ` (attempt ${attempt})` : ""}`);
      lastErr = null;
      break;
     } catch (e) {
      lastErr = e;
      // A flapping backend is worth one more try; a missing card isn't.
      if (attempt < ATTEMPTS) await page_.waitForTimeout(4_000);
     }
    }
    if (lastErr) {
      const msg = lastErr.message.split("\n")[0];
      failed.push(`${shot.name}: ${msg}`);
      console.log(`✗ ${shot.name} — ${msg}`);
    }
  }

  await browser.close();
  await rm(RAW, { recursive: true, force: true });

  const written = (await readdir(OUT)).filter((f) => f.endsWith(".webp"));
  console.log(`\n${written.length} image(s) in ${path.relative(ROOT, OUT)}`);
  if (failed.length) console.log(`${failed.length} failed:\n  ${failed.join("\n  ")}`);
}

await main();
